# Generated by Django 2.0.6 on 2018-12-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('leaf_count', models.PositiveIntegerField(default=0)),
                ('tablet_count', models.PositiveIntegerField(default=0)),
                ('max_pack_count', models.PositiveIntegerField(default=0)),
                ('max_leaf_count', models.PositiveIntegerField(default=0)),
                ('max_tablet_count', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Medicine Details',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('potency', models.CharField(default='', max_length=10)),
                ('price', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('tab', 'Tablet'), ('syr', 'Syrup')], max_length=50)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('accept_date', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Transfer Request',
                'verbose_name_plural': 'Transfer Requests',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Request_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('leaf_count', models.PositiveIntegerField(default=0)),
                ('tablet_count', models.PositiveIntegerField(default=0)),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Medicine')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Transfer_Request')),
            ],
        ),
    ]
