# Generated by Django 2.0.6 on 2018-12-02 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_request',
            name='accepted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer_request',
            name='branchFromid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Branch'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Supplier'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Branch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='med_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Medicine', to_field='name'),
        ),
        migrations.AddField(
            model_name='bill_details',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Bill'),
        ),
        migrations.AddField(
            model_name='bill_details',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Medicine'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Customer'),
        ),
    ]
