# Generated by Django 2.1.4 on 2018-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20181202_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='potency',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
