# Generated by Django 2.1.4 on 2018-12-05 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20181205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_request',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_request',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer_request',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_request',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Received')], max_length=30),
        ),
    ]
