# Generated by Django 2.0.6 on 2018-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='000000000', max_length=15),
        ),
    ]
