# Generated by Django 2.1.4 on 2018-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20181205_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
