# Generated by Django 2.1.4 on 2018-12-06 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20181206_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='phone number must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='cnic must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='000000000', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_username', message='phone number must be numeric', regex='^[0-9]*$')]),
        ),
    ]
