# Generated by Django 2.1.4 on 2018-12-06 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20181206_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='name must be alphabets', regex='^[A-Z][a-z]*$')]),
        ),
    ]
